# Generated by Django 5.1 on 2024-08-10 01:31

import django.db.models.deletion
import sarafan.constants
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=sarafan.constants.NumericalValues[
                            "PRODUCT_CATEGORY_NAME_MAX_LEN"
                        ],
                        verbose_name="Название категории",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=sarafan.constants.NumericalValues[
                            "PRODUCT_CATEGORY_SLUG_MAX_LEN"
                        ],
                        unique=True,
                        verbose_name="Уникальное обозначение категории (слаг).",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="", verbose_name="Изображение категории."
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория продуктов.",
                "verbose_name_plural": "Категории продуктов.",
            },
        ),
        migrations.CreateModel(
            name="ProductSubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=sarafan.constants.NumericalValues[
                            "PRODUCT_CATEGORY_NAME_MAX_LEN"
                        ],
                        verbose_name="Название подкатегории продукта.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=sarafan.constants.NumericalValues[
                            "PRODUCT_CATEGORY_SLUG_MAX_LEN"
                        ],
                        unique=True,
                        verbose_name="Уникальное обозначение подкатегории (слаг).",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="", verbose_name="Изображение подкатегории."
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_members",
                        to="products.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подкатегория продуктов.",
                "verbose_name_plural": "Подкатегории продуктов.",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=sarafan.constants.NumericalValues[
                            "PRODUCT_NAME_MAX_LEN"
                        ],
                        verbose_name="Название продукта.",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=sarafan.constants.NumericalValues[
                            "PRODUCT_CATEGORY_SLUG_MAX_LEN"
                        ],
                        unique=True,
                        verbose_name="Уникальное обозначение продукта (слаг).",
                    ),
                ),
                ("price", models.FloatField(verbose_name="Цена продукта.")),
                (
                    "big_image",
                    models.ImageField(
                        unique=True,
                        upload_to="products/",
                        verbose_name="Изображение продукта 640 x 480.",
                    ),
                ),
                (
                    "mid_image",
                    models.ImageField(
                        blank=True,
                        upload_to="products/",
                        verbose_name="Изображение продукта 320 x 240.",
                    ),
                ),
                (
                    "small_image",
                    models.ImageField(
                        blank=True,
                        upload_to="products/",
                        verbose_name="Изображение продукта 240 x 180.",
                    ),
                ),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.productsubcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="ShopingCart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shoping_cart",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина",
                "verbose_name_plural": "Корзина",
            },
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество продукта."
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="products.product",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="products.shopingcart",
                    ),
                ),
            ],
            options={
                "verbose_name": "Объект корзины.",
                "verbose_name_plural": "Объекты корзины.",
            },
        ),
    ]
